name: QuickInv
author: Guigxs
main: org.guigxs.quickInv.QuickInv
description: Use this plugin to toggle the inventories
api-version: 1.15
version: 1.0
commands:
  gmi:
    description: Set gamemode with new inventory
    usage: "Use : /gmi [player] [gamemode] to change his inventory and gamemode"
    permission: quickInv.gmi
    aliases: [gmi, gamemodeinventory]